// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jjpajouvaovffcfjjqkf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpqcGFqb3V2YW92ZmZjZmpqcWtmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwMjE5NzgsImV4cCI6MjA2ODU5Nzk3OH0.80mIvlUIg35ffB34qWHTeqE9Vm1J754L62dbVASDM1Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});